# gem 'pg', '~> 1.1'
# psql (PostgreSQL) 12.22

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  
 
development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>

test:
  <<: *default
  database: aicruit_api_test

production:
  primary: &primary_production
    <<: *default
    database: aicruit_api_production
    username: aicruit_api
    password: <%= ENV["AICRUIT_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: aicruit_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: aicruit_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: aicruit_api_production_cable
    migrations_paths: db/cable_migrate
