inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'Rakefile'
    - 'config.ru'
    - 'app/controllers/application_controller.rb'
    - 'app/jobs/application_job.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/environments/**/*'
    - 'lib/tasks/**/*'

Metrics/ClassLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
